name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Install Playwright MCP Server
      run: npm install @executeautomation/playwright-mcp-server

    - name: Start MCP Server
      run: npx playwright-mcp start &
      env:
        NODE_ENV: test

    - name: Wait for MCP Server
      run: |
        echo "Waiting for MCP Server to start..."
        sleep 10

    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true
        NODE_ENV: test

    - name: Stop MCP Server
      if: always()
      run: npx playwright-mcp stop

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

    - name: Upload test screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: screenshots/
        retention-days: 30

    - name: Upload test traces
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-traces
        path: traces/
        retention-days: 30 